[Profile0]
Name=default-release
IsRelative=1
Path=1qw3wu2u.default-release
Default=1

# ADD THESE ENTRIES WITH CORRECT PROFILE NUMBERS FOR YOU
[Profile1]
Name=HARDENED
IsRelative=1
Path=499sh1ev.HARDENED
